version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./document_store:/app/document_store/
    environment:
      # Default to Ollama running on the Docker host.
      # Users might need to change host.docker.internal depending on their OS
      # or if Ollama is running in another container or remote.
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      # Set Streamlit specific environment variables if needed, e.g.,
      # - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=1028 
      # (though this is usually configured in Streamlit's config file or command line)
    # If your application needs to wait for Ollama or another service,
    # you might add a healthcheck or depends_on condition here,
    # but for now, we assume Ollama is independently managed and available.

# Optional: Define a top-level volume if you prefer named volumes,
# but bind mounts are often simpler for local development.
# volumes:
#   document_store_data:
